#ru text
titleRu = 'Погода'
placeLabelTextRu = 'Введите город и страну:'
placeInputFieldTextRu = 'Город, страна'
showBtnTextRu = 'Показать'
timeLabelTextRu = 'Текущее время:'
weatherLabelTextRu = 'Текущая погода:'
settingTextRu = 'Настройки'
wrongInputTextRu = 'Неверный ввод'
themeLabelTextRu = 'Тема'
blackThemeTextRu = 'Темная'
lightThemeTextRu = 'Светлая'

#eng text
titleEng = 'Weather'
placeLabelTextEng = 'Input city and country:'
placeInputFieldTextEng = 'City, country'
showBtnTextEng = 'Show'
timeLabelTextEng = 'Cureent time:'
weatherLabelTextEng = 'Current weather:'
settingTextEng = 'Settings'
wrongInputTextEng = 'Wrong input'
themeLabelTextEng = 'Theme'
blackThemeTextEng = 'Dark'
lightThemeTextEng = 'Light'

#universal
langLabelText = 'Язык (Language)'
rusLangText = 'Русский'
engLangText = 'English'
